### ISSUE TITLE
TyperError __init__ 'worker_id'

### ISSUE THREAD

**Issue by svenrr** [yogeshrnaik/camunda-external-task-client-python3#36]
Hi, 
I wanted to try out the example from camunda with python as an external task client: https://docs.camunda.org/get-started/quick-start/deploy/

I have the two following files:
- rest-client 
![image](https://user-images.githubusercontent.com/67638900/112656876-1d010280-8e52-11eb-805f-0f351df8bcba.png)

- external-task-worker
![image](https://user-images.githubusercontent.com/67638900/112656749-fba01680-8e51-11eb-8336-f95635bc3e93.png)

But I got the following error when I start "rest-client". 

![image](https://user-images.githubusercontent.com/67638900/112656071-4e2d0300-8e51-11eb-905a-c8003a64afb3.png)

When I run the same code in juypter notebook I don't get the same error & I get a result in my terminal ("external-task-worker").
Do you know why?

Thanks for help!

**Comment by yogeshrnaik** [comment]
@svenrr
Please try this. 

`ExternalTaskWorker("1", config=...)`

**Comment by svenrr** [comment]
Thanks for the answer but I still get the same error. 
I don't know why it's working in a juypter notebook but not as a script...
